# --- Stage 1: Dependencies ---
FROM node:24-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

# --- Stage 2: Builder ---
FROM node:24-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

# Ignore les erreurs de téléchargement Google Fonts si le réseau est lent
ENV NEXT_FONT_GOOGLE_MOCKED=true

# Passer le build avec le compilateur standard si Turbopack réseau pose problème
RUN npm run build

# --- Stage 3: Runner ---
FROM node:24-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

# Définir l'utilisateur non-root pour la sécurité
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3001

ENV PORT=3001
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]